name: CI

on:
  workflow_dispatch:
  release:
  push:
  pull_request:
    branches: [master]

env:
  NODE_VERSION: 18.18.2
  
jobs:
  ci:
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        os: [macos-13, windows-latest]
        arch: [x64, arm64]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{matrix.arch}})
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Python Distutils for mac
        if: matrix.os == 'macos-13'
        run: |
          python3 -m pip install setuptools

      - name: Install Packages
        run: npm i --ignore-scripts

      - name: Patch Nan
        run: npm run patch-nan
        shell: bash

      - name: Build & Publish Prebuilds
        run: npm run build:ci -- --msvs_version=2022
        env:
          ARCH: ${{ matrix.arch }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
