name: CI

on:
  workflow_dispatch:
  release:
  push:
  pull_request:
    branches: [master]

env:
  ELECTRON_VERSION: 26.0.0  # the specific Electron version
  NODE_VERSION: 18.16.1 # The corresponding node version that electron uses
  
jobs:
  ci:
    strategy:
      matrix:
        os: [macos-13, windows-latest]
        arch: [x64, arm64]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{matrix.arch}})
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Packages
        run: npm i --ignore-scripts

      # Build only if version tag is not present
      - name: Build
        run: npm run build -- --all --msvs_version=2019
        if: startsWith(github.ref, 'refs/tags/v') != true
        env:
          ARCH: ${{ matrix.arch }}

      # Build and publish if version tag is present
      - name: Build & Publish Prebuilds
        run: npm run build:ci -- --msvs_version=2019
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          ARCH: ${{ matrix.arch }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
